services:
  - type: web
    name: super-industries
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: "base64:ImJSmvDrM3ye57niuDvYwcUZoDlrbDl7qp3uLr0sIWw="
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_STORE
        value: array
      - key: SESSION_DRIVER
        value: cookie
